### ISSUE TITLE
Doesn't work inside a docker container running as root

### ISSUE THREAD

**Issue by andrewbelcher** [benoitchantre/setup-ssh-authentication-action#3]
Inside a docker container running as root, `$HOME=/github/home`, meaning the files get written to `/github/home/.ssh`. However, ssh looks for the ssh key/config under `/root/.ssh`.

For reference, `shimataro/ssh-key-action` had [this special case](https://github.com/shimataro/ssh-key-action/blob/b38d88da8a7a230d5eeefd879b038cf3cc4a362c/src/main.ts#L94):
```js
	if(home === "/github/home")
	{
		// Docker container
		return "/root";
	}
```

**Comment by benoitchantre** [comment]
@andrewbelcher Can you make a test with this fix?

```
- name: Configure SSH
  uses: benoitchantre/setup-ssh-authentication-action@8917241edb748ec9e09c9780a0d95acbc34de45b
  with:
    private-key: ...
    ssh-config: ...
    known-hosts: ...

```
